#!/bin/bash

if [[ $1 =~ ^[a-zA-Z][a-zAZ09]+ ]] ;then
    if [[ $1 =~ ^[a-zA-Z][a-zAZ09]+ ]] ;then
        if [[ ! $1 =~ ['!@#$%^&*/\?()-;:.,<>{}،؛÷+']+ ]] ;then
          echo 0
        else
            echo 1
        fi 
    fi
else
    echo 1
fi
