#!/bin/bash

if [ "$(./chkname $1)" -eq 0 ] ;then
    if [ ! -d /home/$USER/project/databases/$1 ] ;then
        mkdir /home/$USER/project/databases/$1
        echo Database created succesfuly
    else
        echo Database already exist
    fi
else
    echo wronge name formate 
fi