#!/bin/bash

checkname=$(/home/$USER/project/scripts/chkname $1)
if [ $checkname -eq 0 ] ;then
    if [ ! -d /home/$USER/project/databases/$1 ] ;then
        mkdir /home/$USER/project/databases/$1
        echo Database created succesfuly
    else
        echo Database already exist
    fi
elif [ $checkname -eq 1 ] ;then
    echo wronge name formate 
elif [ $checkname -eq 2 ] ;then
    echo "You didn't enter any thing Please enter a name"
fi